kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-binding
  namespace: dev-space
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user
subjects:
- kind: Group
  namespace: dev-space
  name: "0888abf7-10de-47c0-872b-667f46a662d3"
  

  